'use client';

import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Loader2, ArrowRight, Sparkles, MessageSquare, User } from 'lucide-react';
import { generateLiveDemo, completeOnboarding } from '../../dashboard/actions';
import { useRouter } from 'next/navigation';

interface Props {
  shop: any;
}

export default function StepDemo({ shop }: Props) {
  const router = useRouter();
  const [state, setState] = useState<'loading' | 'success' | 'skipped'>('loading');
  const [demoReply, setDemoReply] = useState<string | null>(null);
  const [sampleQuestion, setSampleQuestion] = useState('');
  const [completing, setCompleting] = useState(false);

  useEffect(() => {
    const businessType = (shop.business_type || 'retail') as 'retail' | 'restaurant' | 'service';
    generateLiveDemo(shop.id, businessType)
      .then(({ demoReply: reply, sampleQuestion: question }) => {
        setSampleQuestion(question);
        if (reply) {
          setDemoReply(reply);
          setState('success');
        } else {
          setState('skipped');
        }
      })
      .catch(() => {
        setState('skipped');
      });
  }, [shop.id, shop.business_type]);

  const handleFinish = async () => {
    setCompleting(true);
    try {
      await completeOnboarding(shop.id);
      router.push('/dashboard?unlocked=1');
    } catch (e) {
      // Even if this fails, redirect — the gate will re-check
      router.push('/dashboard?unlocked=1');
    }
  };

  return (
    <motion.div
      key="step-demo"
      initial={{ opacity: 0, y: 14 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -14 }}
      className="flex flex-col"
    >
      <div className="text-center mb-6">
        <div className="w-14 h-14 bg-apricot-wash rounded-2xl flex items-center justify-center mx-auto mb-4">
          <Sparkles className="w-7 h-7 text-rust" />
        </div>
        <h1 className="font-serif text-3xl sm:text-4xl text-ink font-light leading-tight tracking-tight">
          {state === 'loading' ? 'Generating your preview…' : state === 'success' ? 'Your AI in action' : 'Almost ready!'}
        </h1>
        <p className="text-xs text-ash mt-2 max-w-sm mx-auto leading-relaxed">
          {state === 'loading'
            ? 'We\'re generating a real AI reply using your shop context.'
            : state === 'success'
            ? 'Here\'s how DullBot answers a sample customer message using your exact setup.'
            : 'Your shop is configured. We\'ll skip the preview and launch your workspace.'}
        </p>
      </div>

      {state === 'loading' && (
        <div className="flex flex-col items-center py-12 gap-4">
          <div className="relative">
            <div className="w-16 h-16 rounded-2xl bg-fog flex items-center justify-center">
              <Loader2 className="w-8 h-8 text-rust animate-spin" />
            </div>
          </div>
          <p className="text-xs text-ash animate-pulse">Talking to Gemini…</p>
        </div>
      )}

      {state === 'success' && demoReply && (
        <div className="bg-fog/40 rounded-cards border border-dove/10 p-5 mb-6">
          {/* Sample customer message */}
          <div className="flex justify-start mb-4">
            <div className="flex items-end gap-2 max-w-[80%]">
              <div className="w-7 h-7 rounded-full bg-dove/30 flex items-center justify-center shrink-0">
                <User className="w-4 h-4 text-ash" />
              </div>
              <div className="bg-white rounded-2xl rounded-bl-sm px-4 py-2.5 shadow-subtle border border-dove/10">
                <p className="text-xs text-ink leading-relaxed">{sampleQuestion}</p>
              </div>
            </div>
          </div>

          {/* AI reply */}
          <div className="flex justify-end">
            <div className="flex items-end gap-2 max-w-[85%]">
              <div className="bg-ink rounded-2xl rounded-br-sm px-4 py-2.5 shadow-subtle">
                <p className="text-xs text-white leading-relaxed whitespace-pre-wrap">{demoReply}</p>
              </div>
              <div className="w-7 h-7 rounded-full bg-rust flex items-center justify-center shrink-0">
                <Sparkles className="w-4 h-4 text-white" />
              </div>
            </div>
          </div>

          <p className="text-[10px] text-ash/50 text-center mt-4 flex items-center justify-center gap-1">
            <Sparkles className="w-3 h-3 text-rust" />
            Generated by Gemini using your business context
          </p>
        </div>
      )}

      <button
        onClick={handleFinish}
        disabled={completing || state === 'loading'}
        className="w-full py-4 bg-rust text-white text-sm font-semibold rounded-buttons hover:bg-rust/90 flex items-center justify-center gap-2 transition-all shadow-subtle disabled:opacity-50 disabled:cursor-not-allowed"
      >
        {completing ? (
          <Loader2 className="w-4 h-4 animate-spin" />
        ) : (
          <>
            <Sparkles className="w-4 h-4" />
            Launch my workspace
          </>
        )}
      </button>
    </motion.div>
  );
}
