export default function SettingsPage() {
  return (
    <div className="max-w-2xl">
      <h1 className="text-2xl font-semibold text-gray-900 mb-6">Settings</h1>
      
      <div className="space-y-6">
        <div className="bg-white p-6 rounded-lg border border-gray-200">
          <h2 className="text-lg font-medium text-gray-900 mb-4">Agent Configuration</h2>
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <label className="text-sm font-medium text-gray-700">Enable AI Agent</label>
                <p className="text-xs text-gray-500">Let DullBot reply to customers automatically.</p>
              </div>
              <input type="checkbox" className="h-4 w-4 text-black focus:ring-black border-gray-300 rounded" defaultChecked />
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Confirmation Tier</label>
              <select className="mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-black focus:border-black sm:text-sm rounded-md">
                <option value="light">Light (Address Only)</option>
                <option value="otp_verified">OTP Verified (SMS)</option>
                <option value="prepay_verified">Prepay Verified (bKash/Nagad)</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">bKash Number</label>
              <input type="text" placeholder="e.g. 017..." className="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-black focus:border-black sm:text-sm" />
              <p className="mt-1 text-xs text-gray-500">The number customers should send money to for prepay verification.</p>
            </div>
          </div>
        </div>
        <div className="bg-white p-6 rounded-lg border border-gray-200 mt-6">
          <h2 className="text-lg font-medium text-gray-900 mb-4">Meta Integration (Messenger & Instagram)</h2>
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Webhook URL (Read-only)</label>
              <input type="text" readOnly value="https://dullbot.vercel.app/api/channels/meta?shop=dull-store" className="mt-1 block w-full bg-gray-50 border border-gray-300 rounded-md shadow-sm py-2 px-3 text-gray-500 sm:text-sm" />
              <p className="mt-1 text-xs text-gray-500">Paste this exact URL into the Facebook Developer Dashboard Webhook settings.</p>
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Verify Token</label>
              <input type="text" placeholder="e.g. my_secure_password_123" className="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-black focus:border-black sm:text-sm" />
              <p className="mt-1 text-xs text-gray-500">Create a secure password. Enter this same password in the Facebook Webhook setup.</p>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Page Access Token</label>
              <input type="password" placeholder="EAAB..." className="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-black focus:border-black sm:text-sm" />
              <p className="mt-1 text-xs text-gray-500">The token generated by Facebook to allow DullBot to send messages as your Page.</p>
            </div>
          </div>
        </div>
        
        <div className="flex justify-end mt-6">
          <button className="bg-black text-white px-4 py-2 rounded-md text-sm font-medium hover:bg-gray-800 transition-colors">
            Save Changes
          </button>
        </div>
      </div>
    </div>
  );
}

